### ISSUE TITLE
The Dataset

### ISSUE THREAD

**Issue by yanjialele** [GauravGajbhiye/SCAMET_RSIC#2]
Hello,author, thank you for your code sharing, could you also provide your processed data set?
![image](https://user-images.githubusercontent.com/51321865/175777504-e9959247-5f12-4ed0-9261-f1356f383a30.png)

**Comment by yanjialele** [comment]
Sorry,I have knowed how to get datasets in your code

**Comment by GauravGajbhiye** [comment]
Thank you for your interest.
