### ISSUE TITLE
Issues with convolutional neural networks

### ISSUE THREAD

**Issue by hongleyingtao** [GauravGajbhiye/SCAMET_RSIC#4]
Hello, can you please provide the code for the convolutional neural network used in this paper? I couldn't find this part in your presentation. Thank you very much!

**Comment by hhBonnie** [comment]
Hello, I would like to ask if you have successfully reproduced this project?

**Comment by GauravGajbhiye** [comment]
Hi @hongleyingtao Thanks for your interest.
In this work, I have used EfficientNetB3 to extract visual features. Please check bottom script of data_extract.py file. I have extracted features using Tensorflow framework and store it as numpy array.
I hope, this will help you to solve your issue.

**Comment by GauravGajbhiye** [comment]
> Hello, I would like to ask if you have successfully reproduced this project?

Sure.. You can reproduce the results. Please make sure to install all libraries and datasets and run all the scripts in proper order.
Thanks.

**Comment by hhBonnie** [comment]
> > Hello, I would like to ask if you have successfully reproduced this project?
> 
> Sure.. You can reproduce the results. Please make sure to install all libraries and datasets and run all the scripts in proper order. Thanks.

Thank you for your prompt reply！

**Comment by hongleyingtao** [comment]
> 您好，我想问一下您是否成功复制了这个项目？

Some of them were successfully debugged

**Comment by hongleyingtao** [comment]
> Hi @hongleyingtao Thanks for your interest. In this work, I have used EfficientNetB3 to extract visual features. Please check bottom script of data_extract.py file. I have extracted features using Tensorflow framework and store it as numpy array. I hope, this will help you to solve your issue.

Hello, I noticed that the EfficientNetB3 network is commented out in the data_extract.py file, is it not used in your implementation? Also, I see that you describe the data_extract_sc/ucm/rsicd.py file in the README as being used for creating the dataset, so it should not be part of the same process as the EfficientNetB3 network extracting visual features from images, right?

**Comment by hongleyingtao** [comment]
> 嗨，感谢您的关注。在这项工作中，我使用EfficientNetB3来提取视觉特征。请检查data_extract.py文件的底部脚本。我使用Tensorflow框架提取了特征并将其存储为numpy数组。我希望，这将帮助您解决您的问题。

And I didn't find the numpy array file in the downloaded data.Thank you very much for taking time out of your busy schedule to answer my questions.

**Comment by GauravGajbhiye** [comment]
> > Hi @hongleyingtao Thanks for your interest. In this work, I have used EfficientNetB3 to extract visual features. Please check bottom script of data_extract.py file. I have extracted features using Tensorflow framework and store it as numpy array. I hope, this will help you to solve your issue.
> 
> Hello, I noticed that the EfficientNetB3 network is commented out in the data_extract.py file, is it not used in your implementation? Also, I see that you describe the data_extract_sc/ucm/rsicd.py file in the README as being used for creating the dataset, so it should not be part of the same process as the EfficientNetB3 network extracting visual features from images, right?

I have commented only "image format conversion" script, which converts any image format into jpeg format. As, sydney-caption dataset has images with tiff image format, you can use commented script to convert it into jpeg. The complete script preprocess textual data for 3 dataset and store the updated captions. The tokenization and image feature extraction process has written for sydney-caption only while same process can be written for rest of the datasets. I would suggest to recompile overall code on your system for better understanding.
Thank you for your concerns.

**Comment by GauravGajbhiye** [comment]
> > 嗨，感谢您的关注。在这项工作中，我使用EfficientNetB3来提取视觉特征。请检查data_extract.py文件的底部脚本。我使用Tensorflow框架提取了特征并将其存储为numpy数组。我希望，这将帮助您解决您的问题。
> 
> And I didn't find the numpy array file in the downloaded data.Thank you very much for taking time out of your busy schedule to answer my questions.

I have not stored the numpy array of image feature. I would suggest to run the code at your end and store it in proper folder for further process. Thanks.

**Comment by hongleyingtao** [comment]
> > > 嗨，感谢您的关注。在这项工作中，我使用EfficientNetB3来提取视觉特征。请检查data_extract.py文件的底部脚本。我使用Tensorflow框架提取了特征并将其存储为numpy数组。我希望，这将帮助您解决您的问题。
> > 
> > 
> > 而且我没有在下载的数据中找到 numpy 数组文件。非常感谢您在百忙之中抽出时间回答我的问题。
> 
> 我没有存储图像功能的numpy数组。我建议在您的终端运行代码并将其存储在适当的文件夹中以供进一步处理。谢谢。

OK,thank you very much!

**Comment by hongleyingtao** [comment]
> > > 嗨，感谢您的关注。在这项工作中，我使用EfficientNetB3来提取视觉特征。请检查data_extract.py文件的底部脚本。我使用Tensorflow框架提取了特征并将其存储为numpy数组。我希望，这将帮助您解决您的问题。
> > 
> > 
> > 您好，我注意到 EfficientNetB3 网络在data_extract.py文件中被注释掉了，它没有在您的实现中使用吗？另外，我看到您将自述文件中的 data_extract_sc/ucm/rsicd.py 文件描述为用于创建数据集，因此它不应该与 EfficientNetB3 网络从图像中提取视觉特征属于同一过程的一部分，对吧？
> 
> 我只评论了“图像格式转换”脚本，该脚本可将任何图像格式转换为 jpeg 格式。由于悉尼字幕数据集具有 tiff 图像格式的图像，因此您可以使用注释脚本将其转换为 jpeg。完整的脚本预处理 3 个数据集的文本数据并存储更新的标题。标记化和图像特征提取过程仅针对 sydney-caption 编写，而可以为其余数据集编写相同的过程。我建议在您的系统上重新编译整体代码以更好地理解。感谢您的关注。

 OK,thank you very much!
